"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SPINALTWIN_ADMIN_SERVICE_APP_RELATION_TYPE_PTR_LST = exports.HAS_API_IN_GROUP_RELATION = exports.HAS_API_IN_CONTEXT_RELATION = exports.ADD_DIGITALTWIN = exports.URL_BOS_CONFIG = exports.CREDENTIAL_ADMIN_TO_BOS = exports.CREDENTIAL_BOS_TO_ADMIN = exports.REGISTER_ADMIN = exports.HUB_USER = exports.APP_PROFILE_LIST_CONTEXT = exports.USER_PROFILE_LIST_CONTEXT = exports.ORGAN_LIST_CONTEXT = exports.API_LIST_CONTEXT = exports.ROLE_LIST_CONTEXT = exports.DATA_LIST_CONTEXT = exports.USER_LIST_CONTEXT = exports.SPINALTWIN_DESCRIPTION_CONTEXT = void 0;
exports.SPINALTWIN_DESCRIPTION_CONTEXT = 'SpinalTwinDescription';
exports.USER_LIST_CONTEXT = 'UserList';
exports.DATA_LIST_CONTEXT = 'DigitalTwin';
exports.ROLE_LIST_CONTEXT = 'RoleList';
exports.API_LIST_CONTEXT = 'ApiList';
exports.ORGAN_LIST_CONTEXT = 'OrganList';
exports.USER_PROFILE_LIST_CONTEXT = 'UserProfileList';
exports.APP_PROFILE_LIST_CONTEXT = 'AppProfileList';
exports.HUB_USER = "HubUser";
exports.REGISTER_ADMIN = 'RegisterAdmin';
exports.CREDENTIAL_BOS_TO_ADMIN = 'CredentialBosAdmin';
exports.CREDENTIAL_ADMIN_TO_BOS = 'CredentialAdminBos';
exports.URL_BOS_CONFIG = process.env.URL_BOS_APP;
exports.ADD_DIGITALTWIN = 'hasDigitalTwin';
exports.HAS_API_IN_CONTEXT_RELATION = 'hasApiInContext';
exports.HAS_API_IN_GROUP_RELATION = 'hasApi';
exports.SPINALTWIN_ADMIN_SERVICE_APP_RELATION_TYPE_PTR_LST = 'PtrLst';
//# sourceMappingURL=constant.js.map